import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 5, 3, 4])
y = np.array([1, 2, 3, 1])

# Line of best fit (linear regression line)
'''
slope, intercept = np.polyfit(x, y, 1)
line = slope * x + intercept

plt.plot(x, line)
plt.scatter(x, line)
plt.scatter(x, y)
'''

# IMPORTANT: any curved graph can be achieved by obtaining a large set of x-values using np.linspace(),
# then feeding those x-values into a function you have to obtain the y-values.

# Parabola generated by plotting a ton a x value points, then feeding through a function
'''
a = 1
b = 0
c = 0

x = np.linspace(-10, 10, 100)

y = a * x**2 + b * x + c



plt.scatter(x, y)
plt.plot(x, y, color="red")
'''


x = np.linspace(-5, 5, 1000)
sine = np.sin(2 * np.pi * x)
poly = x ** 3 + 2
expo = np.exp(-2 * x)

plt.plot(x, sine)
plt.plot(x, poly)
plt.plot(x, expo)
plt.show()
